estitle: "Andrew Cobble"
author: "Andrew Cobble"
description: "University of Texas at Dallas"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "SmallIndex.md", title: "Home"}
  - {file: "Portfolio.md", title: "Portfolio"}
  - {file: "ContactInformation.md", title: "Contact"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:cobblekandrew@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/C0bb13"}
  - {title: LinkedIn, icon: linkedin-in, url: "https://www.linkedin.com/in/andrew-cobble-aaa318199/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-seo-tag

